packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '3': true
  '"': true
  ',': true
  '-': true
  '[': true
  ']': true
  b: true
  better-sqlite3: false
  d: true
  e: true
  esbuild: false
  i: true
  l: true
  q: true
  r: true
  s: true
  t: true
  u: true
